name: Rust-static-build
on:
  push:
    tags:
      - "v*.*.*"

env:
  CARGO_TERM_COLOR: always
  BUILD_TARGET: x86_64-unknown-linux-musl
  BINARY_NAME: bcat
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@44c2b7a8a4ea60a981eaca3cf939b5f4305c123b # v4
      - name: Build-musl
        uses: gmiam/rust-musl-action@master
        with:
          args: cargo build --target $BUILD_TARGET --release
      - uses: actions/upload-artifact@v4
        with:
          name: ${{ env.BINARY_NAME }}
          path: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: target/x86_64-unknown-linux-musl/release/${{ env.BINARY_NAME }}
          prerelease: ${{ contains(github.ref, '-beta') }}

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
